// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lottery/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgClaimOwner struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *MsgClaimOwner) Reset()         { *m = MsgClaimOwner{} }
func (m *MsgClaimOwner) String() string { return proto.CompactTextString(m) }
func (*MsgClaimOwner) ProtoMessage()    {}
func (*MsgClaimOwner) Descriptor() ([]byte, []int) {
	return fileDescriptor_16a4f365e1c6455d, []int{0}
}
func (m *MsgClaimOwner) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimOwner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimOwner.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimOwner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimOwner.Merge(m, src)
}
func (m *MsgClaimOwner) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimOwner) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimOwner.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimOwner proto.InternalMessageInfo

func (m *MsgClaimOwner) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type MsgClaimOwnerResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (m *MsgClaimOwnerResponse) Reset()         { *m = MsgClaimOwnerResponse{} }
func (m *MsgClaimOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClaimOwnerResponse) ProtoMessage()    {}
func (*MsgClaimOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16a4f365e1c6455d, []int{1}
}
func (m *MsgClaimOwnerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimOwnerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimOwnerResponse.Merge(m, src)
}
func (m *MsgClaimOwnerResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimOwnerResponse proto.InternalMessageInfo

func (m *MsgClaimOwnerResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type MsgChangeOwner struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	NewOwner string `protobuf:"bytes,2,opt,name=newOwner,proto3" json:"newOwner,omitempty"`
}

func (m *MsgChangeOwner) Reset()         { *m = MsgChangeOwner{} }
func (m *MsgChangeOwner) String() string { return proto.CompactTextString(m) }
func (*MsgChangeOwner) ProtoMessage()    {}
func (*MsgChangeOwner) Descriptor() ([]byte, []int) {
	return fileDescriptor_16a4f365e1c6455d, []int{2}
}
func (m *MsgChangeOwner) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgChangeOwner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgChangeOwner.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgChangeOwner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgChangeOwner.Merge(m, src)
}
func (m *MsgChangeOwner) XXX_Size() int {
	return m.Size()
}
func (m *MsgChangeOwner) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgChangeOwner.DiscardUnknown(m)
}

var xxx_messageInfo_MsgChangeOwner proto.InternalMessageInfo

func (m *MsgChangeOwner) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgChangeOwner) GetNewOwner() string {
	if m != nil {
		return m.NewOwner
	}
	return ""
}

type MsgChangeOwnerResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (m *MsgChangeOwnerResponse) Reset()         { *m = MsgChangeOwnerResponse{} }
func (m *MsgChangeOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*MsgChangeOwnerResponse) ProtoMessage()    {}
func (*MsgChangeOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16a4f365e1c6455d, []int{3}
}
func (m *MsgChangeOwnerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgChangeOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgChangeOwnerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgChangeOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgChangeOwnerResponse.Merge(m, src)
}
func (m *MsgChangeOwnerResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgChangeOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgChangeOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgChangeOwnerResponse proto.InternalMessageInfo

func (m *MsgChangeOwnerResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type MsgSetupLottery struct {
	Creator     string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	EntranceFee uint64 `protobuf:"varint,2,opt,name=entranceFee,proto3" json:"entranceFee,omitempty"`
}

func (m *MsgSetupLottery) Reset()         { *m = MsgSetupLottery{} }
func (m *MsgSetupLottery) String() string { return proto.CompactTextString(m) }
func (*MsgSetupLottery) ProtoMessage()    {}
func (*MsgSetupLottery) Descriptor() ([]byte, []int) {
	return fileDescriptor_16a4f365e1c6455d, []int{4}
}
func (m *MsgSetupLottery) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetupLottery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetupLottery.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetupLottery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetupLottery.Merge(m, src)
}
func (m *MsgSetupLottery) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetupLottery) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetupLottery.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetupLottery proto.InternalMessageInfo

func (m *MsgSetupLottery) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSetupLottery) GetEntranceFee() uint64 {
	if m != nil {
		return m.EntranceFee
	}
	return 0
}

type MsgSetupLotteryResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (m *MsgSetupLotteryResponse) Reset()         { *m = MsgSetupLotteryResponse{} }
func (m *MsgSetupLotteryResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetupLotteryResponse) ProtoMessage()    {}
func (*MsgSetupLotteryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16a4f365e1c6455d, []int{5}
}
func (m *MsgSetupLotteryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetupLotteryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetupLotteryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetupLotteryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetupLotteryResponse.Merge(m, src)
}
func (m *MsgSetupLotteryResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetupLotteryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetupLotteryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetupLotteryResponse proto.InternalMessageInfo

func (m *MsgSetupLotteryResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type MsgChangeEntranceFee struct {
	Creator        string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	NewEntranceFee uint64 `protobuf:"varint,2,opt,name=newEntranceFee,proto3" json:"newEntranceFee,omitempty"`
}

func (m *MsgChangeEntranceFee) Reset()         { *m = MsgChangeEntranceFee{} }
func (m *MsgChangeEntranceFee) String() string { return proto.CompactTextString(m) }
func (*MsgChangeEntranceFee) ProtoMessage()    {}
func (*MsgChangeEntranceFee) Descriptor() ([]byte, []int) {
	return fileDescriptor_16a4f365e1c6455d, []int{6}
}
func (m *MsgChangeEntranceFee) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgChangeEntranceFee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgChangeEntranceFee.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgChangeEntranceFee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgChangeEntranceFee.Merge(m, src)
}
func (m *MsgChangeEntranceFee) XXX_Size() int {
	return m.Size()
}
func (m *MsgChangeEntranceFee) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgChangeEntranceFee.DiscardUnknown(m)
}

var xxx_messageInfo_MsgChangeEntranceFee proto.InternalMessageInfo

func (m *MsgChangeEntranceFee) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgChangeEntranceFee) GetNewEntranceFee() uint64 {
	if m != nil {
		return m.NewEntranceFee
	}
	return 0
}

type MsgChangeEntranceFeeResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (m *MsgChangeEntranceFeeResponse) Reset()         { *m = MsgChangeEntranceFeeResponse{} }
func (m *MsgChangeEntranceFeeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgChangeEntranceFeeResponse) ProtoMessage()    {}
func (*MsgChangeEntranceFeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16a4f365e1c6455d, []int{7}
}
func (m *MsgChangeEntranceFeeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgChangeEntranceFeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgChangeEntranceFeeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgChangeEntranceFeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgChangeEntranceFeeResponse.Merge(m, src)
}
func (m *MsgChangeEntranceFeeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgChangeEntranceFeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgChangeEntranceFeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgChangeEntranceFeeResponse proto.InternalMessageInfo

func (m *MsgChangeEntranceFeeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type MsgEnterLottery struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *MsgEnterLottery) Reset()         { *m = MsgEnterLottery{} }
func (m *MsgEnterLottery) String() string { return proto.CompactTextString(m) }
func (*MsgEnterLottery) ProtoMessage()    {}
func (*MsgEnterLottery) Descriptor() ([]byte, []int) {
	return fileDescriptor_16a4f365e1c6455d, []int{8}
}
func (m *MsgEnterLottery) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgEnterLottery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgEnterLottery.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgEnterLottery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgEnterLottery.Merge(m, src)
}
func (m *MsgEnterLottery) XXX_Size() int {
	return m.Size()
}
func (m *MsgEnterLottery) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgEnterLottery.DiscardUnknown(m)
}

var xxx_messageInfo_MsgEnterLottery proto.InternalMessageInfo

func (m *MsgEnterLottery) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type MsgEnterLotteryResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (m *MsgEnterLotteryResponse) Reset()         { *m = MsgEnterLotteryResponse{} }
func (m *MsgEnterLotteryResponse) String() string { return proto.CompactTextString(m) }
func (*MsgEnterLotteryResponse) ProtoMessage()    {}
func (*MsgEnterLotteryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16a4f365e1c6455d, []int{9}
}
func (m *MsgEnterLotteryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgEnterLotteryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgEnterLotteryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgEnterLotteryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgEnterLotteryResponse.Merge(m, src)
}
func (m *MsgEnterLotteryResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgEnterLotteryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgEnterLotteryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgEnterLotteryResponse proto.InternalMessageInfo

func (m *MsgEnterLotteryResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type MsgStartLottery struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *MsgStartLottery) Reset()         { *m = MsgStartLottery{} }
func (m *MsgStartLottery) String() string { return proto.CompactTextString(m) }
func (*MsgStartLottery) ProtoMessage()    {}
func (*MsgStartLottery) Descriptor() ([]byte, []int) {
	return fileDescriptor_16a4f365e1c6455d, []int{10}
}
func (m *MsgStartLottery) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgStartLottery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgStartLottery.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgStartLottery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStartLottery.Merge(m, src)
}
func (m *MsgStartLottery) XXX_Size() int {
	return m.Size()
}
func (m *MsgStartLottery) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStartLottery.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStartLottery proto.InternalMessageInfo

func (m *MsgStartLottery) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type MsgStartLotteryResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (m *MsgStartLotteryResponse) Reset()         { *m = MsgStartLotteryResponse{} }
func (m *MsgStartLotteryResponse) String() string { return proto.CompactTextString(m) }
func (*MsgStartLotteryResponse) ProtoMessage()    {}
func (*MsgStartLotteryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16a4f365e1c6455d, []int{11}
}
func (m *MsgStartLotteryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgStartLotteryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgStartLotteryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgStartLotteryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStartLotteryResponse.Merge(m, src)
}
func (m *MsgStartLotteryResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgStartLotteryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStartLotteryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStartLotteryResponse proto.InternalMessageInfo

func (m *MsgStartLotteryResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type MsgEndLottery struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *MsgEndLottery) Reset()         { *m = MsgEndLottery{} }
func (m *MsgEndLottery) String() string { return proto.CompactTextString(m) }
func (*MsgEndLottery) ProtoMessage()    {}
func (*MsgEndLottery) Descriptor() ([]byte, []int) {
	return fileDescriptor_16a4f365e1c6455d, []int{12}
}
func (m *MsgEndLottery) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgEndLottery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgEndLottery.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgEndLottery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgEndLottery.Merge(m, src)
}
func (m *MsgEndLottery) XXX_Size() int {
	return m.Size()
}
func (m *MsgEndLottery) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgEndLottery.DiscardUnknown(m)
}

var xxx_messageInfo_MsgEndLottery proto.InternalMessageInfo

func (m *MsgEndLottery) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type MsgEndLotteryResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (m *MsgEndLotteryResponse) Reset()         { *m = MsgEndLotteryResponse{} }
func (m *MsgEndLotteryResponse) String() string { return proto.CompactTextString(m) }
func (*MsgEndLotteryResponse) ProtoMessage()    {}
func (*MsgEndLotteryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16a4f365e1c6455d, []int{13}
}
func (m *MsgEndLotteryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgEndLotteryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgEndLotteryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgEndLotteryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgEndLotteryResponse.Merge(m, src)
}
func (m *MsgEndLotteryResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgEndLotteryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgEndLotteryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgEndLotteryResponse proto.InternalMessageInfo

func (m *MsgEndLotteryResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*MsgClaimOwner)(nil), "lotterychainnel.lottery.MsgClaimOwner")
	proto.RegisterType((*MsgClaimOwnerResponse)(nil), "lotterychainnel.lottery.MsgClaimOwnerResponse")
	proto.RegisterType((*MsgChangeOwner)(nil), "lotterychainnel.lottery.MsgChangeOwner")
	proto.RegisterType((*MsgChangeOwnerResponse)(nil), "lotterychainnel.lottery.MsgChangeOwnerResponse")
	proto.RegisterType((*MsgSetupLottery)(nil), "lotterychainnel.lottery.MsgSetupLottery")
	proto.RegisterType((*MsgSetupLotteryResponse)(nil), "lotterychainnel.lottery.MsgSetupLotteryResponse")
	proto.RegisterType((*MsgChangeEntranceFee)(nil), "lotterychainnel.lottery.MsgChangeEntranceFee")
	proto.RegisterType((*MsgChangeEntranceFeeResponse)(nil), "lotterychainnel.lottery.MsgChangeEntranceFeeResponse")
	proto.RegisterType((*MsgEnterLottery)(nil), "lotterychainnel.lottery.MsgEnterLottery")
	proto.RegisterType((*MsgEnterLotteryResponse)(nil), "lotterychainnel.lottery.MsgEnterLotteryResponse")
	proto.RegisterType((*MsgStartLottery)(nil), "lotterychainnel.lottery.MsgStartLottery")
	proto.RegisterType((*MsgStartLotteryResponse)(nil), "lotterychainnel.lottery.MsgStartLotteryResponse")
	proto.RegisterType((*MsgEndLottery)(nil), "lotterychainnel.lottery.MsgEndLottery")
	proto.RegisterType((*MsgEndLotteryResponse)(nil), "lotterychainnel.lottery.MsgEndLotteryResponse")
}

func init() { proto.RegisterFile("lottery/tx.proto", fileDescriptor_16a4f365e1c6455d) }

var fileDescriptor_16a4f365e1c6455d = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x4f, 0xef, 0xd2, 0x40,
	0x10, 0xa5, 0xfe, 0xc5, 0x41, 0x51, 0x1b, 0x15, 0xd2, 0x98, 0x06, 0x7b, 0x40, 0x8c, 0xa1, 0x55,
	0x88, 0x89, 0x89, 0x37, 0x4d, 0x39, 0xd9, 0x98, 0x94, 0x8b, 0xf1, 0x56, 0xcb, 0xa4, 0x60, 0xea,
	0xb6, 0xd9, 0x5d, 0x02, 0x7c, 0x0b, 0x3f, 0x96, 0x47, 0x8e, 0x1e, 0x0d, 0x7c, 0x0a, 0x6f, 0x86,
	0x52, 0xca, 0x16, 0xf8, 0x6d, 0xf7, 0x77, 0x9c, 0xed, 0x9b, 0xf7, 0xde, 0x4c, 0xe6, 0xa5, 0xf0,
	0x28, 0x4e, 0x38, 0x47, 0xba, 0x72, 0xf8, 0xd2, 0x4e, 0x69, 0xc2, 0x13, 0xbd, 0x95, 0xbf, 0x84,
	0xd3, 0x60, 0x46, 0x08, 0xc6, 0x76, 0x5e, 0x5b, 0xaf, 0xe0, 0x81, 0xc7, 0xa2, 0x4f, 0x71, 0x30,
	0xfb, 0xf9, 0x65, 0x41, 0x90, 0xea, 0x6d, 0xb8, 0x1b, 0x52, 0x0c, 0x78, 0x42, 0xdb, 0x5a, 0x47,
	0xeb, 0xdd, 0xf3, 0x0f, 0xa5, 0xf5, 0x16, 0x9e, 0x96, 0xa0, 0x3e, 0xb2, 0x34, 0x21, 0x0c, 0x77,
	0x2d, 0x6c, 0x1e, 0x86, 0xc8, 0x58, 0xd6, 0x52, 0xf7, 0x0f, 0xa5, 0x35, 0x82, 0xe6, 0xae, 0x65,
	0x1a, 0x90, 0x08, 0x2b, 0xe8, 0x75, 0x03, 0xea, 0x04, 0x17, 0x19, 0xaa, 0x7d, 0x23, 0xfb, 0x54,
	0xd4, 0xd6, 0x00, 0x9e, 0x95, 0x79, 0x14, 0xb4, 0x3d, 0x78, 0xe8, 0xb1, 0x68, 0x8c, 0x7c, 0x9e,
	0x7e, 0xde, 0x0f, 0x2b, 0x11, 0xef, 0x40, 0x03, 0x09, 0xa7, 0x01, 0x09, 0x71, 0x84, 0x98, 0xe9,
	0xdf, 0xf2, 0xc5, 0x27, 0x6b, 0x08, 0xad, 0x13, 0x3a, 0x05, 0x0f, 0x5f, 0xe1, 0x49, 0xe1, 0xdb,
	0x3d, 0x92, 0x49, 0x8c, 0x74, 0xa1, 0x49, 0x70, 0xe1, 0x9e, 0x79, 0x39, 0x79, 0xb5, 0xde, 0xc3,
	0xf3, 0x4b, 0xcc, 0x0a, 0x9e, 0x5e, 0x67, 0x7b, 0x71, 0x09, 0x47, 0x5a, 0xb9, 0x97, 0x7c, 0x6a,
	0x11, 0xac, 0xac, 0x30, 0xe6, 0x01, 0xe5, 0xaa, 0x0a, 0x22, 0x58, 0x41, 0x61, 0x7f, 0xb5, 0x2e,
	0x99, 0x54, 0xf3, 0xef, 0xaf, 0xf6, 0x08, 0xad, 0x66, 0x1f, 0xfc, 0xbb, 0x0d, 0x37, 0x3d, 0x16,
	0xe9, 0x13, 0x00, 0x21, 0x18, 0x5d, 0xfb, 0x8a, 0x0c, 0xd9, 0xa5, 0x54, 0x18, 0xb6, 0x1a, 0xae,
	0xf0, 0x11, 0x41, 0x43, 0x0c, 0xc8, 0x4b, 0x69, 0xfb, 0x11, 0x68, 0x38, 0x8a, 0xc0, 0x42, 0xe8,
	0x07, 0xdc, 0x2f, 0xa5, 0xa1, 0x27, 0x23, 0x10, 0x91, 0xc6, 0x1b, 0x55, 0x64, 0xa1, 0xb5, 0x82,
	0xc7, 0xe7, 0x57, 0xdf, 0xaf, 0x76, 0x2c, 0xc0, 0x8d, 0x77, 0xd7, 0x82, 0x8b, 0x63, 0x96, 0x8e,
	0x5b, 0x3a, 0xa6, 0x88, 0x94, 0x8f, 0x79, 0x31, 0x03, 0xbb, 0x95, 0x8a, 0x67, 0x2e, 0x5f, 0xa9,
	0x80, 0xac, 0x58, 0xe9, 0xa5, 0x34, 0x4c, 0x00, 0x84, 0x83, 0xef, 0xca, 0xbd, 0x1e, 0x70, 0xf2,
	0x6b, 0x3c, 0x4f, 0xc5, 0xc7, 0x0f, 0xbf, 0x37, 0xa6, 0xb6, 0xde, 0x98, 0xda, 0xdf, 0x8d, 0xa9,
	0xfd, 0xda, 0x9a, 0xb5, 0xf5, 0xd6, 0xac, 0xfd, 0xd9, 0x9a, 0xb5, 0x6f, 0x2f, 0xf2, 0xc6, 0x7e,
	0xc6, 0xd4, 0x27, 0x18, 0x3b, 0x4b, 0xa7, 0xf8, 0xd1, 0xac, 0x52, 0x64, 0xdf, 0xef, 0x64, 0x3f,
	0x9b, 0xe1, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfc, 0xe6, 0x6b, 0xe9, 0x80, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	ClaimOwner(ctx context.Context, in *MsgClaimOwner, opts ...grpc.CallOption) (*MsgClaimOwnerResponse, error)
	ChangeOwner(ctx context.Context, in *MsgChangeOwner, opts ...grpc.CallOption) (*MsgChangeOwnerResponse, error)
	SetupLottery(ctx context.Context, in *MsgSetupLottery, opts ...grpc.CallOption) (*MsgSetupLotteryResponse, error)
	ChangeEntranceFee(ctx context.Context, in *MsgChangeEntranceFee, opts ...grpc.CallOption) (*MsgChangeEntranceFeeResponse, error)
	EnterLottery(ctx context.Context, in *MsgEnterLottery, opts ...grpc.CallOption) (*MsgEnterLotteryResponse, error)
	StartLottery(ctx context.Context, in *MsgStartLottery, opts ...grpc.CallOption) (*MsgStartLotteryResponse, error)
	EndLottery(ctx context.Context, in *MsgEndLottery, opts ...grpc.CallOption) (*MsgEndLotteryResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ClaimOwner(ctx context.Context, in *MsgClaimOwner, opts ...grpc.CallOption) (*MsgClaimOwnerResponse, error) {
	out := new(MsgClaimOwnerResponse)
	err := c.cc.Invoke(ctx, "/lotterychainnel.lottery.Msg/ClaimOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ChangeOwner(ctx context.Context, in *MsgChangeOwner, opts ...grpc.CallOption) (*MsgChangeOwnerResponse, error) {
	out := new(MsgChangeOwnerResponse)
	err := c.cc.Invoke(ctx, "/lotterychainnel.lottery.Msg/ChangeOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetupLottery(ctx context.Context, in *MsgSetupLottery, opts ...grpc.CallOption) (*MsgSetupLotteryResponse, error) {
	out := new(MsgSetupLotteryResponse)
	err := c.cc.Invoke(ctx, "/lotterychainnel.lottery.Msg/SetupLottery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ChangeEntranceFee(ctx context.Context, in *MsgChangeEntranceFee, opts ...grpc.CallOption) (*MsgChangeEntranceFeeResponse, error) {
	out := new(MsgChangeEntranceFeeResponse)
	err := c.cc.Invoke(ctx, "/lotterychainnel.lottery.Msg/ChangeEntranceFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) EnterLottery(ctx context.Context, in *MsgEnterLottery, opts ...grpc.CallOption) (*MsgEnterLotteryResponse, error) {
	out := new(MsgEnterLotteryResponse)
	err := c.cc.Invoke(ctx, "/lotterychainnel.lottery.Msg/EnterLottery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) StartLottery(ctx context.Context, in *MsgStartLottery, opts ...grpc.CallOption) (*MsgStartLotteryResponse, error) {
	out := new(MsgStartLotteryResponse)
	err := c.cc.Invoke(ctx, "/lotterychainnel.lottery.Msg/StartLottery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) EndLottery(ctx context.Context, in *MsgEndLottery, opts ...grpc.CallOption) (*MsgEndLotteryResponse, error) {
	out := new(MsgEndLotteryResponse)
	err := c.cc.Invoke(ctx, "/lotterychainnel.lottery.Msg/EndLottery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	ClaimOwner(context.Context, *MsgClaimOwner) (*MsgClaimOwnerResponse, error)
	ChangeOwner(context.Context, *MsgChangeOwner) (*MsgChangeOwnerResponse, error)
	SetupLottery(context.Context, *MsgSetupLottery) (*MsgSetupLotteryResponse, error)
	ChangeEntranceFee(context.Context, *MsgChangeEntranceFee) (*MsgChangeEntranceFeeResponse, error)
	EnterLottery(context.Context, *MsgEnterLottery) (*MsgEnterLotteryResponse, error)
	StartLottery(context.Context, *MsgStartLottery) (*MsgStartLotteryResponse, error)
	EndLottery(context.Context, *MsgEndLottery) (*MsgEndLotteryResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ClaimOwner(ctx context.Context, req *MsgClaimOwner) (*MsgClaimOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimOwner not implemented")
}
func (*UnimplementedMsgServer) ChangeOwner(ctx context.Context, req *MsgChangeOwner) (*MsgChangeOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeOwner not implemented")
}
func (*UnimplementedMsgServer) SetupLottery(ctx context.Context, req *MsgSetupLottery) (*MsgSetupLotteryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetupLottery not implemented")
}
func (*UnimplementedMsgServer) ChangeEntranceFee(ctx context.Context, req *MsgChangeEntranceFee) (*MsgChangeEntranceFeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeEntranceFee not implemented")
}
func (*UnimplementedMsgServer) EnterLottery(ctx context.Context, req *MsgEnterLottery) (*MsgEnterLotteryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnterLottery not implemented")
}
func (*UnimplementedMsgServer) StartLottery(ctx context.Context, req *MsgStartLottery) (*MsgStartLotteryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartLottery not implemented")
}
func (*UnimplementedMsgServer) EndLottery(ctx context.Context, req *MsgEndLottery) (*MsgEndLotteryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndLottery not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ClaimOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaimOwner)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClaimOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lotterychainnel.lottery.Msg/ClaimOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClaimOwner(ctx, req.(*MsgClaimOwner))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ChangeOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgChangeOwner)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ChangeOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lotterychainnel.lottery.Msg/ChangeOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ChangeOwner(ctx, req.(*MsgChangeOwner))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetupLottery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetupLottery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetupLottery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lotterychainnel.lottery.Msg/SetupLottery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetupLottery(ctx, req.(*MsgSetupLottery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ChangeEntranceFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgChangeEntranceFee)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ChangeEntranceFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lotterychainnel.lottery.Msg/ChangeEntranceFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ChangeEntranceFee(ctx, req.(*MsgChangeEntranceFee))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_EnterLottery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgEnterLottery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).EnterLottery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lotterychainnel.lottery.Msg/EnterLottery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).EnterLottery(ctx, req.(*MsgEnterLottery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_StartLottery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgStartLottery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).StartLottery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lotterychainnel.lottery.Msg/StartLottery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).StartLottery(ctx, req.(*MsgStartLottery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_EndLottery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgEndLottery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).EndLottery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lotterychainnel.lottery.Msg/EndLottery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).EndLottery(ctx, req.(*MsgEndLottery))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lotterychainnel.lottery.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClaimOwner",
			Handler:    _Msg_ClaimOwner_Handler,
		},
		{
			MethodName: "ChangeOwner",
			Handler:    _Msg_ChangeOwner_Handler,
		},
		{
			MethodName: "SetupLottery",
			Handler:    _Msg_SetupLottery_Handler,
		},
		{
			MethodName: "ChangeEntranceFee",
			Handler:    _Msg_ChangeEntranceFee_Handler,
		},
		{
			MethodName: "EnterLottery",
			Handler:    _Msg_EnterLottery_Handler,
		},
		{
			MethodName: "StartLottery",
			Handler:    _Msg_StartLottery_Handler,
		},
		{
			MethodName: "EndLottery",
			Handler:    _Msg_EndLottery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lottery/tx.proto",
}

func (m *MsgClaimOwner) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimOwner) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimOwner) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimOwnerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimOwnerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimOwnerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Success {
		i--
		if m.Success {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgChangeOwner) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgChangeOwner) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgChangeOwner) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NewOwner) > 0 {
		i -= len(m.NewOwner)
		copy(dAtA[i:], m.NewOwner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NewOwner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgChangeOwnerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgChangeOwnerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgChangeOwnerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Success {
		i--
		if m.Success {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetupLottery) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetupLottery) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetupLottery) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EntranceFee != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EntranceFee))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetupLotteryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetupLotteryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetupLotteryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Success {
		i--
		if m.Success {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgChangeEntranceFee) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgChangeEntranceFee) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgChangeEntranceFee) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NewEntranceFee != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.NewEntranceFee))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgChangeEntranceFeeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgChangeEntranceFeeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgChangeEntranceFeeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Success {
		i--
		if m.Success {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgEnterLottery) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgEnterLottery) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgEnterLottery) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgEnterLotteryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgEnterLotteryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgEnterLotteryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Success {
		i--
		if m.Success {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgStartLottery) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgStartLottery) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgStartLottery) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgStartLotteryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgStartLotteryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgStartLotteryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Success {
		i--
		if m.Success {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgEndLottery) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgEndLottery) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgEndLottery) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgEndLotteryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgEndLotteryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgEndLotteryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Success {
		i--
		if m.Success {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgClaimOwner) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgClaimOwnerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Success {
		n += 2
	}
	return n
}

func (m *MsgChangeOwner) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.NewOwner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgChangeOwnerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Success {
		n += 2
	}
	return n
}

func (m *MsgSetupLottery) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.EntranceFee != 0 {
		n += 1 + sovTx(uint64(m.EntranceFee))
	}
	return n
}

func (m *MsgSetupLotteryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Success {
		n += 2
	}
	return n
}

func (m *MsgChangeEntranceFee) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.NewEntranceFee != 0 {
		n += 1 + sovTx(uint64(m.NewEntranceFee))
	}
	return n
}

func (m *MsgChangeEntranceFeeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Success {
		n += 2
	}
	return n
}

func (m *MsgEnterLottery) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgEnterLotteryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Success {
		n += 2
	}
	return n
}

func (m *MsgStartLottery) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgStartLotteryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Success {
		n += 2
	}
	return n
}

func (m *MsgEndLottery) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgEndLotteryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Success {
		n += 2
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgClaimOwner) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimOwner: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimOwner: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimOwnerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimOwnerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimOwnerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Success = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgChangeOwner) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgChangeOwner: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgChangeOwner: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewOwner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewOwner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgChangeOwnerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgChangeOwnerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgChangeOwnerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Success = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetupLottery) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetupLottery: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetupLottery: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EntranceFee", wireType)
			}
			m.EntranceFee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EntranceFee |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetupLotteryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetupLotteryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetupLotteryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Success = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgChangeEntranceFee) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgChangeEntranceFee: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgChangeEntranceFee: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewEntranceFee", wireType)
			}
			m.NewEntranceFee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NewEntranceFee |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgChangeEntranceFeeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgChangeEntranceFeeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgChangeEntranceFeeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Success = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgEnterLottery) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgEnterLottery: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgEnterLottery: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgEnterLotteryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgEnterLotteryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgEnterLotteryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Success = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgStartLottery) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgStartLottery: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgStartLottery: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgStartLotteryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgStartLotteryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgStartLotteryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Success = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgEndLottery) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgEndLottery: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgEndLottery: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgEndLotteryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgEndLotteryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgEndLotteryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Success = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
