accounts:
    - name: alice
      coins: ["10000token", "200000000stake"]
    - name: bob
      coins: ["10000token", "100000000stake"]
    - name: lewis
      coins: ["10000token"]
    - name: george
      coins: ["10000token"]
    - name: valtteri
      coins: ["10000token"]
validator:
    name: alice
    staked: "100000000stake"
client:
    openapi:
        path: "docs/static/openapi.yml"
    vuex:
        path: "vue/src/store"
faucet:
    name: bob
    coins: ["5token", "100000stake"]
